version: 2
jobs:
  build:
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
      - GITHUB_ORG: https://GH_TOKEN@github.io/GlidingTracks
      - GITHUB_NAME: gt-autodeploy
      - NAME: gt-frontend

    branches:
      ignore:
        - gh-pages

    working_directory: ~/$NAME

    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout

      - restore_cache:
          key: gt-frontend-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: gt-frontend-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter

      - run:
          name: Run unit tests
          command: |
            ./cc-test-reporter before-build
            xvfb-run -a npm run test -- --code-coverage --watch=false --progress=false --browsers=ChromeNoSandbox
            ./cc-test-reporter after-build --debug --coverage-input-type lcov --exit-code $?

      #- run: xvfb-run -a npm run e2e -- --config=protractor-ci.conf.js

      - run:
          name: Deploy on Github Pages
          command: |
            ng build --prod
            npx ngh --repo "$GITHUB_ORG/$NAME.git"
                    --name "$GITHUB_NAME"
                    --dir "dist/$NAME"
