version: 2
jobs:
  build:

    working_directory: ~/gt-frontend

    docker:
    - image: circleci/node:8-browsers

    steps:
    - checkout

    - restore_cache:
        key: gt-frontend-{{ .Branch }}-{{ checksum "package.json" }}

    - run: npm install

    - save_cache:
        key: gt-frontend-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - "node_modules"

    - run: xvfb-run -a npm run test -- --watch=false --progress=false --browsers=ChromeNoSandbox
    #- run: xvfb-run -a npm run e2e -- --config=protractor-ci.conf.js
